[package]
name = "port-scanner"
version = "0.1.0"
authors = ["teruya <abas.trace.on@gmail.com>"]
edition = "2018"

[dependencies]
pnet = "0.22.0"
rand = "0.6"
serde = "1"
serde_json = "1"
rayon = "1.0"
